export const STARTUP_DETAILS_REQUEST = 'STARTUP_DETAILS_REQUEST'
export const STARTUP_DETAILS_SUCCESS = 'STARTUP_DETAILS_SUCCESS'
export const STARTUP_DETAILS_FAIL = 'STARTUP_DETAILS_FAIL'

export const STARTUP_DELETE_REQUEST = 'STARTUP_DELETE_REQUEST'
export const STARTUP_DELETE_SUCCESS = 'STARTUP_DELETE_SUCCESS'
export const STARTUP_DELETE_FAIL = 'STARTUP_DELETE_FAIL'

export const STARTUP_CREATE_REQUEST = 'STARTUP_CREATE_REQUEST'
export const STARTUP_CREATE_SUCCESS = 'STARTUP_CREATE_SUCCESS'
export const STARTUP_CREATE_FAIL = 'STARTUP_CREATE_FAIL'
export const STARTUP_CREATE_RESET = 'STARTUP_CREATE_RESET'

export const STARTUP_UPDATE_REQUEST = 'STARTUP_UPDATE_REQUEST'
export const STARTUP_UPDATE_SUCCESS = 'STARTUP_UPDATE_SUCCESS'
export const STARTUP_UPDATE_FAIL = 'STARTUP_UPDATE_FAIL'
export const STARTUP_UPDATE_RESET = 'STARTUP_UPDATE_RESET'
